$apps = @(
# General MS Store Apps
#	@("Amazon", "Amazon.com.Amazon_343d40qqvtj1t"),
	@("Amazon Alexa", "57540AMZNMobileLLC.AmazonAlexa_22t9g3sebte08\LocalState\Alexa"),
	@("Amazon Prime Video", "AmazonVideo.PrimeVideo_pwbj9vvecjh7j\LocalCache\Roaming"),
	@("Booking.com", "PricelinePartnerNetwork.Booking.comUSABigsavingson_mgae2k3ys4ra0\DUMMYDIR"),
	@("Candy Crush Friends", "king.com.CandyCrushFriends_kgqvnymyfvs32\LocalState\Documents"),
	@("Candy Crush Saga", "king.com.CandyCrushSaga_kgqvnymyfvs32\LocalState\Documents"),
	@("Clipchamp", "Clipchamp.Clipchamp_yxz26nhyzhsrt\LocalState\EBWebView"),
	@("Dropbox for S-Mode", "C27EB4BA.Dropbox_xbfy0k16fey96\SystemAppData\Helium")
	@("Dropbox Promotion", "C27EB4BA.DropboxOEM_xbfy0k16fey96\SystemAppData\Helium"),
	@("DisneyPlus", "Disney.37853FC22B2CE_6rarf9sa4v8jt\LocalState\Sentry"),
	@("Dolby Access", "DolbyLaboratories.DolbyAccess_rz1tebttyb220\LocalState\Microsoft"),
	@("ESPN", "22364Disney.ESPN*\DUMMYDIR"),
	@("Facebook", "FACEBOOK.FACEBOOK_8xx8rvfyw5nnt\DUMMYDIR"),
	@("Family", "MicrosoftCorporationII.MicrosoftFamily_8wekyb3d8bbwe\LocalState\EBWebView\BrowserMetrics-spare.pma"),
	@("Feedback Hub", "Microsoft.WindowsFeedbackHub_8wekyb3d8bbwe\DUMMYDIR"),
	@("Hulu", "HULULLC.HULUPLUS_fphbd361v8tya\DUMMYDIR"),
	@("Instagram", "Facebook.Instagram*\DUMMYDIR"),
	@("Messenger", "FACEBOOK.317180B0BB486_8xx8rvfyw5nnt\AC\Messenger\TamStorage"),
	@("Microsoft Journal", "Microsoft.MicrosoftJournal_8wekyb3d8bbwe\SystemAppData\Helium"),
	@("Microsoft News", "Microsoft.BingNews_8wekyb3d8bbwe\LocalState\EBWebView"),
	@("Microsoft Sudoku", "Microsoft.MicrosoftSudoku_8wekyb3d8bbwe\LocalState\VungleSDK"),
#	@("Microsoft Teams", "MicrosoftTeams_8wekyb3d8bbwe\LocalCache\Microsoft\MSTeams\EBWebView"),
	@("Microsoft Weather", "Microsoft.BingWeather_8wekyb3d8bbwe\LocalState\Cache"),
	@("Microsoft To Do", "Microsoft.Todos_8wekyb3d8bbwe\AC\Microsoft"),
	@("Microsoft Whiteboard", "Microsoft.Whiteboard_8wekyb3d8bbwe\SystemAppData\Helium"),
	@("Minecraft Education Edition", "Microsoft.MinecraftEducationEdition_8wekyb3d8bbwe\LocalState\games"),
	@("Mixed Reality Portal", "Microsoft.MixedReality.Portal_8wekyb3d8bbwe\AC\Microsoft"),
	@("Netflix", "4DF9E0F8.Netflix_mcm4njqhnhss8\DUMMYDIR"),
	@("People", "Microsoft.People_8wekyb3d8bbwe\LocalState\SRPData.xml"),
#	@("Phone Link", "Microsoft.YourPhone_8wekyb3d8bbwe\SystemAppData\Helium"),
#	@("Realtek Audio Console", "RealtekSemiconductorCorp.RealtekAudioControl_dt26b99r8h8gj\DUMMYDIR"),
	@("Skype", "Microsoft.SkypeApp_kzf8qxf38zg5c\LocalCache\Roaming\Microsoft\Skype for Store"),
	@("Spotify", "SpotifyAB.SpotifyMusic_zpdnekdrzrea0\LocalCache\Roaming"),
#	@("Sticky Notes", "Microsoft.MicrosoftStickyNotes_8wekyb3d8bbwe\LocalState\profile"),
	@("Tiktok", "BytedancePte.Ltd.TikTok_6yccndn6064se\DUMMYDIR"),
	@("Tips", "Microsoft.Getstarted_8wekyb3d8bbwe\DUMMYDIR"),
	@("Twitter", "9E2F88E3.TWITTER_wgeqdkkx372wm\DUMMYDIR"),
	@("Whatsapp", "5319275A.WhatsAppDesktop_cv1g1gvanyjgm\LocalState\Microsoft"),
	@("Windows Maps", "Microsoft.WindowsMaps_8wekyb3d8bbwe\LocalState\Collections"),
#	@("Xbox", "Microsoft.GamingApp_8wekyb3d8bbwe"),
#	@("Xbox Console Companion", "Microsoft.XboxApp_8wekyb3d8bbwe\LocalState\SmartGlass"),
#	@("Xbox Game Bar", "Microsoft.XboxGamingOverlay_8wekyb3d8bbwe\LocalState\DiagOutputDir"),
#	@("Xbox Game Bar Plugin", "Microsoft.XboxGameOverlay_8wekyb3d8bbwe"),
#	@("Xbox Identity Provider", "Microsoft.XboxIdentityProvider_8wekyb3d8bbwe"),
#	@("Xbox Game Speech Window", "Microsoft.XboxSpeechToTextOverlay_8wekyb3d8bbwe"),
#	@("Xbox Live", "Microsoft.Xbox.TCUI_8wekyb3d8bbwe"),
# Acer OEM MS Store Apps
# ASUS OEM MS Store Apps
#	@("Armoury Crate", "B9ECED6F.ArmouryCrate_qmba6cd70vzyy"),
#	@("Aura Creator", "B9ECED6F.AURACreator_qmba6cd70vzyy"),
#	@("MyASUS", "B9ECED6F.ASUSPCAssistant_qmba6cd70vzyy"),
# Dell OEM MS Store Apps
#	@("Dell Cinema Color", "PortraitDisplays.DellCinemaColor_2dgmkzkw4h30c"),
	@("Dell Customer Connect", "DellInc.DellCustomerConnect_htrsf667h5kn2\DUMMYDIR"),
	@("Dell Digital Delivery", "DellInc.DellDigitalDelivery_htrsf667h5kn2\DUMMYDIR"),
#	@("Dell SupportAssist", "DellInc.DellSupportAssistforPCs_htrsf667h5kn2"),
	@("Killer Control Center", "RivetNetworks.KillerControlCenter_rh07ty8m5nkag\SystemAppData\Helium"),
	@("My Dell", "DellInc.MyDell_htrsf667h5kn2\DUMMYDIR"),
	@("SmartByte", "RivetNetworks.SmartByte_rh07ty8m5nkag\DUMMYDIR"),
#	@("Waves MaxxAudio", "WavesAudio.MaxxAudioProforDell2022_fh4rh281wavaa"),
# HP OEM MS Store Apps
#	@("Bang & Olufsen Audio Control", "AD2F1837.BangOlufsenAudioControl_v10z8vjag6ke6"),
	@("Energy Star", "AD2F1837.HPInc.EnergyStar_v10z8vjag6ke6\DUMMYDIR"),
	@("HP Audio Center", "AD2F1837.HPAudioCenter_v10z8vjag6ke6"),
#	@("HP Command Center", "AD2F1837.HPThermalControl_v10z8vjag6ke6"),
#	@("HP Enhanced Lighting", " AD2F1837.HPEnhance_v10z8vjag6ke6"),
	@("HP JumpStart", "AD2F1837.HPJumpStarts_v10z8vjag6ke6\DUMMYDIR"),
#	@("HP Pen Control Plus", "AD2F1837.HPPenControlPlus_v10z8vjag6ke6"),
	@("HP Privacy Settings", "AD2F1837.HPPrivacySettings_v10z8vjag6ke6\DUMMYDIR"),
	@("HP QuickDrop", "AD2F1837.HPQuickDrop_v10z8vjag6ke6\DUMMYDIR"),
#	@("HP Smart", "AD2F1837.HPInc.EnergyStar_v10z8vjag6ke6\DUMMYDIR"),
#	@("HP System Event Utility", "AD2F1837.HPSystemEventUtility_v10z8vjag6ke6"),
	@("MyHP", "AD2F1837.myHP_v10z8vjag6ke6\DUMMYDIR"),
#	@("Omen Gaming Hub", "AD2F1837.OMENCommandCenter_v10z8vjag6ke6"),
	@("Random Salad Games Solitaire", "26720RandomSaladGamesLLC.3899848563C1F_kx24dqmazqk8j\LocalCache\cdState.txt"),
	@("Random Salad Games Solitaire |Alt|", "26720RandomSaladGamesLLC.SimpleSolitaire_kx24dqmazqk8j\LocalCache\cdState.txt"),
# Lenovo OEM MS Store Apps
#	@("Lenovo Hotkeys", "E0469640.LenovoUtility_5grkq8ppsgwt4\DUMMYDIR"),
#	@("Lenovo Pen", "WacomTechnologyCorp.157535B83C264_ss941bf8mfs8a\DUMMYDIR"),
#	@("Lenovo Smart Appearance, "E0469640.SmartAppearance_5grkq8ppsgwt4\DUMMYDIR"),
	@("Lenovo Voice", "E046963F.LenovoVoiceWorldWide_k1h2ywk1493x8\DUMMYDIR"),
	@("Mirkat", "Mirkat.Mirkat_hm0vq9nycmfde\SystemAppData\Helium\User.dat")
# MSI OEM MS Store Apps
# Razer OEM MS Store Apps
# Samsung OEM MS Store Apps,
)