$programs = [ordered]@{
    'Remote Access' = @(
        'Alpemix'
        'AnyDesk'
        'AweSun'
        'GlanceGuest'
        'GoToAssist'
        'LogMeIn'
        'OptimumDesk'
        'Optimum Desk'
        'Remote Assistance'
        'RemotePC'
        'Remote Utilities'
        'Splashtop'
        'Supremo'
        'TeamViewer'
        'UltraViewer'
        'UltraVNC'
        'VNC Connect'
        'Zoho Assist'
    )
    'Anti-Virus' = @(
        'McAfee'
        'WebAdvisor by McAfee'
    )
    'Malware' = @(
        'Advanced System Care'
        'Altruistics'
        'Avast Secure Browser'
        'Avery Teoma Search App'
        'BBWC'
        'Bonefreeze'
        'Browser Assistant'
        'BrowserAssistant'
        'Browser Extension'
        'Clear'
        'ClearBar'
        'ClientPCSpeedup'
        'Deepteep'
        'Driver Easy'
        'DriverEasy'
        'Driver Support One'
        'Driver Tonic'
        'Driver Tuner'
        'DriverUpdate'
        'Easy Radio Player'
        'EstimateSpeedUp'
        'GetMyDrivers'
        'iTop Easy Desktop'
        'iTop VPN'
        'iTop Screen Recorder'
        'Malware Crusher'
        'N9 Firewall'
        'OneLaunch'
        'OneStart'
        'PC App Store'
        'PDFHub'
        'PremierOpinion'
        'PrivDog'
        'Quick Driver Updater'
        'RelevantKnowledge'
        'RestMinder'
        'Restoro'
        'screensearchutils'
        'ScreensRecorder'
        'Simple PC Optimizer'
        'Solve iQ'
        'SSOption'
        'SlimCleaner Plus'
        'System Mechanic'
        'Viewndow'
        'WaveBrowser'
        'WeatherApp'
        'Web Companion'
        'WebDiscover Browser'
        'WebBar Toolbar'
        'WinZip'
    )
    'Bloatware' = @(
    # General Manual Uninstallers
        'Google Toolbar for Internet Explorer'
        'Windows PC Health Check'
    # Acer OEM Manual Uninstallers
    # ASUS OEM Manual Uninstallers
        'ASUS AI Recovery'
        'ASUS FancyStart'
        'ASUS Live Update'
        'ASUS Power4Gear Hybrid'
        'ASUS SmartLogon'
        'ASUS Splendid Video Enhancement Technology'
        'ASUS Virtual Camera'
        'ASUS WebStorage'
        'ASUS Welcome'
        'AsusVibe'
    # Dell OEM Manual Uninstallers
        'Dell Customer Connect'
        'Dell Digital Delivery'
        'Dell Digital Delivery Services'
        'Dell Help & Support'
        'Dell Mobile Connect Driver'
        'Dell Product Registration'
        'Dell Shop'
        'Fusion Service'
        'QuickSet64'
        'SmartByte'
        'SmartByte Drivers & Services'
    # HP OEM Manual Uninstallers
        'Bonjour'
        'Duet Display'
        'ExpressVPN'
        'HP Documentation'
        'HP Connection Optimizer'
        'HP Jumpstart Apps'
        'HP Jumpstart Bridge'
        'HP Jumpstart Launch'
        'WildTangent Games'
        'WildTangent Helper'
        'WildTangent Shortcut Provider'
    # Lenovo OEM Manual Uninstallers
        'Lenovo Smart Appearance Components'
        'Lenovo Voice Service'
        'Lenovo Welcome'
        'Smart Note'
    # MSI OEM Manual Uninstallers
    # Razer OEM Manual Uninstallers
    # Samsung OEM Manual Uninstallers
        'BatteryLifeExtender'
        'Easy Content Share'
        'Easy Display Manager'
        'Easy Display Manager Option'
        'Easy Migration'
        'Easy Network Manager'
        'Easy Network Manager Help'
        'EasyFileShare'
        'Fast Start'
        'Movie Color Enhancer'
        'Movie Color Enhancer Option'
        'Samsung Support Center'
        'Samsung Update Plus'
        'Samsung Update Plust Help'
    )
}