$quips = @(
	"Acer? I hardly even know her!",
	"Clicked 'remind me later' on updates... for the 100th time?",
	"CTRL+Z'ing your tech oopsies.",
	"Forgot to back it up? Of course you did.",
	"Forgot to plug it in? For the love of...",
	"I regret checking this one's search history...",
	"Loading... only '90s kids will remember.",
	"Now with extra ATOMs!",
	"Paid for WinRAR? We need to talk.",
	"Password123? Really?",
	"Stop calling 'Microsoft'!",
	"Sure, I can tuneup this...Celeron?",
	"Tech issue? Or just user issue?",
	"Tech issues? We CTRL+ALT+DEFEAT them!",
	"Tech issues? We've seen worse. Promise.",
	"Tech whisperers: Less horse, more hardware.",
	"That 'Free Download' wasn't so free, huh?",
	"Tried turning it off and on? Of course you didn't.",
	"Typed 'Google' into Google? We can't even...",
	"Webcam broken? *flips privacy shutter*",
	"We do IT so you won't throw IT.",
	"We know your browser history. Still here to help.",
	"We turn it off and on so you don't have to!",
	"WiFi broken? *flips Airplane Mode toggle*",
	"Yes, we can fix your...CPU...",
	"You didn't just try to download free RAM... did you?",
	"Your antivirus is on vacation. We're not.",
	"Your PC has more viruses than a petri dish. We got this."
)