$quips = @(
    "7-Zip > Winrar. Yeah, I said it.",
    "Acer? I hardly even know her!",
    "A clean desktop? Clearly a psychopath.",
    "Ah, the cloud. Someone else's computer.",
    "BitLocker: Because your files needed a safe word.",
    "C:\Taxes? Bold. Reckless, but bold.",
    "Cable management is just bondage for nerds.",
    "Click harder. That usually helps.",
    "Clicked 'remind me later' on updates...for the 100th time?",
    "Clippy walked so Copilot could hallucinate.",
    "Closing the lid is not a proper shutdown.",
    "CTRL+Z'ing your tech oopsies.",
    "Did you just type 'Google' into Google?",
    "Every loose C:\ file shortens an admin's life.",
    "Forgot to back it up? Not surprised.",
    "Have you tried turning it off and back on?",
    "Have you tried unchecking 'Enable Viruses'?",
    "I don't think CCleaner is going to fix whatever this is.",
    "I regret checking this one's search history...",
    "Incognito mode hides your history, but not the shame.",
    "Keyboard filthy enough to gain sentience.",
    "Keyboard not responding. Press any key to continue.",
    "Let's delete System32 and call it a day.",
    "Loading... only '90s kids will remember.",
    "Malwarebytes just whispered, 'Dear God.'",
    "Microsoft Edge: Chrome with trust issues.",
    "Nothing says confidence like taping the password to the screen.",
    "Now with extra ATOMs!",
    "One can only accidentally install WinZip so many times...",
    "One HDMI port, three VGA adapters, zero hope."
    "OneDrive has entered its gaslighting era.",
    "Paid for WinRAR? We need to talk.",
    "Password123? Really?",
    "RAM is temporary. Regret is forever.",
    "ScreenConnectClient? My rival...",
    "Sure, I can tuneup this...Celeron?",
    "Tech whisperers: Less horse, more hardware.",
    "That 'Free Download' wasn't so free after all.",
    "That's not 'Microsoft' trying to call you.",
    "User error detected. Applying diplomacy.",
    "Warranty? Expired during the Stone Age.",
    "Wave Browser? I see you enjoy clicking 'Free Download'.",
    "Webcam broken? *flips privacy shutter*",
    "We do IT so you won't throw IT.",
    "We found the issue. It's Windows.",
    "We know your browser history. Still here to help.",
    "We turn it off and on so you don't have to!",
    "WiFi broken? *flips Airplane Mode toggle*",
    "Yes, we can fix your...CPU...",
    "You didn't just try to download free RAM... did you?",
    "Your uptime is impressive and deeply upsetting."
)